#ifndef OPTION_H
#define OPTION_H

#include <stdbool.h>
#include "settings.h"


#if SETTINGS_SHOW_CAPACITY
    #define OPTION_COUNT 4
#else
    #define OPTION_COUNT 3
#endif

#define OPTION_UNIT_CURRENT   0
#define OPTION_UNIT_VOLTAGE   1
#define OPTION_UNIT_POWER     2
#define OPTION_UNIT_CAPACITY  3

#define OPTION_UNITTYPE_CURRENT_AVG       0
#define OPTION_UNITTYPE_CURRENT_MAX       1
#define OPTION_UNITTYPE_CURRENT_MIN       2
#define OPTION_UNITTYPE_VOLTAGE_AVG       3
#define OPTION_UNITTYPE_VOLTAGE_MAX       4
#define OPTION_UNITTYPE_VOLTAGE_MIN       5
#define OPTION_UNITTYPE_POWER_AVG         6
#define OPTION_UNITTYPE_POWER_MAX         7
#define OPTION_UNITTYPE_POWER_MIN         8
#define OPTION_UNITTYPE_CAPACITY_MINUTE   9
#define OPTION_UNITTYPE_CAPACITY_HOUR    10
#define OPTION_UNITTYPE_CAPACITY_NA      11

#endif
